from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='home'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('tools', views.tools, name='tools'),
    path('policy', views.policy, name='policy'),
    path('privacy', views.privacy, name='privacy'),
    path('terms', views.terms, name='terms'),
    path('disclaimer', views.disclaimer, name='disclaimer'),
    path('video', views.video, name='video'),
    path('upload_video/', views.upload_video, name='upload_video'),
    path('image/', views.image, name='image'),
    path('image/imagegif', views.image_gif, name='imagegif'),
    path('document/', views.document, name='document'),
    path('download/<str:title>/', views.download_file, name="download"),
    path('gif/<str:name>/', views.gif, name="gif"),
    path('image/imageico', views.image_ico, name='imageico'),
    path('ico/<str:na>/', views.ico, name="ico"),
    path('image/imagepdf', views.image_pdf, name='imagepdf'),
    path('pdf/<str:name>/', views.pdf, name="pdf"),
    path('document/doc_pdf', views.doc_pdf, name='doc_pdf'),
    path('pdfs/<str:titles>/', views.pdfs, name="pdfs"),
    path('document/pdf_doc', views.pdf_doc, name='pdf_doc'),
    path('doc/<str:titles>/', views.doc, name="doc"),
    path('document/imagepdf', views.image_pdf, name='imagepdf'),

    path('tgif', views.image_gif, name='tgif'),
    path('tico', views.image_ico, name='tico'),
    path('tpdf', views.image_pdf, name='tpdf'),
    path('tvideo', views.upload_video, name='tvideo'),
    path('tdoc', views.doc_pdf, name='tdoc'),
    path('tpdfs', views.pdf_doc, name='tpdfs'),
    # path('remove_post/<int:id>/', views.remove_post, name='remove_post'),
    # path('remove_playlist/<int:id>/', views.remove_playlist, name='remove_playlist'),
    # path('login/', views.login, name='login'),
    # path('register/', views.register, name='register'),
    # path('contact/', views.contact, name='contact'),
    # path('logout/', views.logoutuser, name='logout'),
    # path('profile/', views.profile, name='profile'),
    # path('create_playlist/', views.playlist, name='playlist'),
    # path('watch_playlist/', views.see_playlist, name='see_playlist'),

]
